<?php
$z[0]=Array("channelartlist","\r\n          <li class=\"tab2 drop-menu-effect\"><a href=\"{dede:field name='typeurl'/}\" class=\"s-navli\">{dede:field name='typename'/}</a>\r\n            <ul class=\"submenu\">\r\n              {dede:channel type='son' noself='yes'}\r\n              <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",431,861);
$z[0][4]['typeid']="top";

?>